export const SET_LOADING = "SET_LOADING";
export const SET_USERS = "SET_USERS";
export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const GET_USER_REQUESTED = "GET_USER_REQUESTED";
